# Generated by Django 3.1.6 on 2021-02-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210202_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
