# Generated by Django 3.1.6 on 2021-02-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=14, null=True)),
                ('ddd', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, max_length=2, null=True)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ficha_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('telefone_adicional', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'prod_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True)),
                ('custo', models.TextField()),
                ('preco', models.TextField()),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField()),
                ('valor_total', models.TextField()),
                ('forma_pagamento', models.CharField(max_length=200)),
                ('parc', models.SmallIntegerField(blank=True, null=True)),
                ('valor_pago', models.TextField()),
                ('desconto', models.TextField()),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_prd', models.IntegerField()),
            ],
            options={
                'db_table': 'venda_produto',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
    ]
